name: 03 - Workflow Runners

on:
  workflow-dispatch:

jobs:
  ubunutu-echo:
    runs-on:
      ubuntu-latest
    steps:
      - name: Show OS
        run: | # multiline command
          echo "This job is running on an Ubuntu runner"
          echo "Runner OS: ${{RUNNER.OS}}"
  windows-echo:
    runs-on:
      windows-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a Windows runner"
          echo "Runner OS: ${{RUNNER.OS}}"
  mac-echo:
    runs-on:
      macos-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a MacOS runner"
          echo "Runner OS: ${{RUNNER.OS}}"
