name: 04 - Using Actions

on:
  push:

jobs:
  build:
    runs-on:
      ubuntu-latest
    
    steps:
      # 0. Checkout e code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # 1. Install dependencies of our React application
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      # 2. Execute automated tests
      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app