name: 04 - Using Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app # View React app in the folder 04-using-actions
    steps:
      # 0. Checkout e code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing folders
        run: ls
      # 1. Install dependencies of our React application
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Install Dependencies
        run: npm ci # It will install dependencies from defaults:run:working-directory
        # working-directory: 04-using-actions/react-app
      # 2. Execute automated tests
      - name: Run Unit Tests
        run: npm run test
        # working-directory: 04-using-actions/react-app