name: 13 - Using Caching

on:
  workflow_dispatch: 
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        type: choice
        options:
          - 22.x
          - 24.x
          - 25.x
        default: 22.x


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app # Set folder 13-caching/react-app for all the run commands (ex: npm ci, npm run tests)
    # 1. Checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      # 2. Install dependencies
      - name: Install dependencies
        run: npm ci
      # 3. Linting, formatting, unit testing, building
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      # 4. Deploy to a nonprod environment
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"

