name: 13 - Using Caching

on:
  workflow_dispatch: 
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        type: choice
        options:
          - 22.x
          - 24.x
          - 25.x
        default: 22.x


jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app # Set folder 13-caching/react-app for all the run commands (ex: npm ci, npm run tests)
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    # 1. Checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      # 2. Install dependencies
      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json')}}" >> "$GITHUB_OUTPUT"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  lint-test:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app # Set folder 13-caching/react-app for all the run commands (ex: npm ci, npm run tests)
    # 1. Checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      # 2. Install dependencies
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
          # key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json')}}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci
      # 3. Linting, formatting, unit testing, building
      - name: Testing
        run: npm run test
      - name: Linting
        run: echo "Linting..."
      # - name: Building
      #   run: npm run build
      # 4. Deploy to a nonprod environment
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app # Set folder 13-caching/react-app for all the run commands (ex: npm ci, npm run tests)
    # 1. Checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      # 2. Install dependencies
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci
      # building
      - name: Building
        run: npm run build
      # 4. Deploy to a nonprod environment
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"

